[build]
  base = "client"  # Specify the directory where the build command should run
  publish = "."    # Publish directory for the client build output

[[redirects]]
  from = "/api/*"
  to = "https://botchatserver.netlify.app/api/:splat"  # Proxy requests to the server
  status = 200
